Many fixes - support deploying the WAR file, too

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -2,14 +2,9 @@
 set -euo pipefail
 
 [ -v BASE_DIR ] || BASE_DIR="/app"
+[ -v FILE_DIR ] || FILE_DIR="${BASE_DIR}/file"
 [ -v CONF_DIR ] || CONF_DIR="${BASE_DIR}/conf"
 [ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"
-[ -v CONFIG_ZIP ] || CONFIG_ZIP="${BASE_DIR}/.arkcase.zip"
-[ -v VERSION_MARKER ] || VERSION_MARKER="${CONF_DIR}/.version"
-[ -v EXTRACT_MARKER ] || EXTRACT_MARKER="${CONF_DIR}/acm/acm-config-server-repo/arkcase.yaml"
-EXTRACT_TARGET="$(mktemp -d -p "${CONF_DIR}")"
-COMPLETE="false"
-FILES=()
 
 say() {
 	echo -e "$(date -u -Isec): ${@}"
@@ -18,15 +13,6 @@ say() {
 fail() {
 	say "${@}" 1>&2
 	exit ${EXIT_CODE:-1}
-}
-
-to_boolean() {
-	local RESULT="false"
-	case "${1,,}" in
-		true | t | yes | y | 1 | on | enable | enabled | active ) RESULT="true" ;;
-	esac
-	echo "${RESULT}"
-	return 0
 }
 
 list_files() {
@@ -40,107 +26,84 @@ list_files() {
 	fi
 }
 
-cleanup() {
-	rm -rf "${EXTRACT_TARGET}" &>/dev/null
-	if "${COMPLETE}" ; then
-		say "Initialization complete."
-	else
-		say "Initialization was not complete. Cleaning out the extracted files"
-		# Make sure the marker file is gone
-		rm -rf "${VERSION_MARKER}" || true
-		# Just in case ...
-		for f in "${FILES[@]}" ; do
-			f="${CONF_DIR}/${f}"
-			[ -e "${f}" ] || continue
-			rm -rf "${f}" || true
-		done
+install_file() {
+	local SRC="${1}"
+	local TGT="${2}"
+
+	if [ ! -f "${SRC}" ] ; then
+		say "There is no source file [${SRC}]"
+		return 1
 	fi
+
+	if [ ! -d "${TGT}" ] ; then
+		say "There is no destination directory [${TGT}], will skip deploying the file [${SRC}]"
+		return 0
+	fi
+
+	local SUM=""
+	[ -f "${SRC}.sum" ] && SUM="$(cat "${SRC}.sum")"
+
+	if [[ ! "${SUM,,}" =~ ^[0-9a-f]{64}$ ]] ; then
+		say "Failed to find the cached checksum for [${SRC}], or its contents are invalid. Computing it directly..."
+		read SUM REST < <(sha256sum "${SUM}")
+		if [[ ! "${SUM,,}" =~ ^[0-9a-f]{64}$ ]] ; then
+			say "Failed to compute the sha256 checksum for [${SRC}]"
+			return 1
+		fi
+	fi
+
+	local MARK="${TGT}/.version"
+	if [ -e "${MARK}" ] ; then
+		local DATE=""
+		local EXISTING=""
+		local EXISTING_LOADED="false"
+		local OLD_SUM="<none>"
+
+		if [ -e "${MARK}" ] ; then
+			# We explicitly don't call sort b/c we want to get the last record on the list,
+			# regardless of its contents
+			read DATE OLD_SUM EXISTING < <(grep -v '^[[:space:]]*#' "${MARK}" | grep -v '^[[:space:]]*$' | tail -1)
+			EXISTING_LOADED="true"
+		fi
+
+		if "${EXISTING_LOADED}" && [ "${SUM}" == "${OLD_SUM}" ] ; then
+			say "The file [${SRC}] appears to already be deployed into [${TGT}] since ${DATE} (version = ${EXISTING}, verified by checksum)."
+			return 0
+		fi
+
+		say "File content change detected for [${SRC}] through file checksum:\n\tEXISTING: [${EXISTING} = ${OLD_SUM}]\n\tINCOMING: [${VER} = ${SUM}]"
+	else
+		say "The configuration doesn't appear to be deployed, or version tracking hasn't yet begun (the marker path [${MARK}] is missing)"
+	fi
+
+	# It's OK to do this, as TGT is meant to be a volume in this container
+	# TODO: Do we want to support multiple file types? tar? tar.gz? tgz? tar.bz2? tbz2? tar.xz? txz? etc?
+	unzip -o -d "${TGT}" "${SRC}"
+
+	# Add the marker record for this version
+	echo -e "$(date -u -Ins) ${SUM} ${VER}" >> "${MARK}"
 }
 
-trap cleanup exit
+[ -v VER ] || VER="(unknown)"
+[ -z "${VER}" ] || VER="(unknown)"
+
+while read FILE ; do
+	F="${FILE##*/}"
+	F="${F%%.*}"
+
+	D="${BASE_DIR}/${F}"
+	install_file "${FILE}" "${D}" || fail "Failed to deploy the file [${FILE}] into [${D}]"
+done < <(find "${FILE_DIR}" -mindepth 1 -maxdepth 1 -type f -name '*.zip')
 
 #
-# Step one: extract the configurations
+# This is the only fix we know must be applied FOR SURE each time
 #
-
-# Make a note of the incoming file's checksum
-if [ -f "${CONFIG_ZIP}.sum" ] ; then
-	SRC_SUM="$(cat "${CONFIG_ZIP}.sum")" || true
-fi
-
-if [[ ! "${SRC_SUM,,}" =~ ^[0-9a-f]{64}$ ]] ; then
-	say "Failed to find the cached checksum, or it's invalid. Computing it directly..."
-	read SRC_SUM REST < <(sha256sum "${CONFIG_ZIP}")
-fi
-
-# If we're not given a version number, use a substitute
-[ -v VER ] || VER="(unspecified)"
-
-if [ -e "${EXTRACT_MARKER}" ] ; then
-	DATE=""
-	EXISTING=""
-	EXISTING_LOADED="false"
-
-	if [ -e "${VERSION_MARKER}" ] ; then
-		read DATE SUM EXISTING < <(grep -v '^[[:space:]]*#' "${VERSION_MARKER}" | grep -v '^[[:space:]]*$' | tail -1)
-		EXISTING_LOADED="true"
-	else
-		SUM="<none>"
-	fi
-
-	if "${EXISTING_LOADED}" && [ "${SRC_SUM}" == "${SUM}" ] ; then
-		COMPLETE="true"
-		say "The current configuration appears to already be deployed since ${DATE} (${VER})."
-		exit 0
-	fi
-
-	say "File content change detected through file checksum: existing:\n\tEXISTING: [${SUM}]\n\tINCOMING: [${SRC_SUM}]"
-else
-	say "The configuration doesn't appear to be deployed, the marker path [${EXTRACT_MARKER}] is missing"
-fi
-
-[ -d "${CONF_DIR}" ] || fail "Failed to CD into the configuration mount point [${CONF_DIR}]"
-
-# It's OK to do this, as CONF_DIR is meant to be a volume in this container
-unzip -o -d "${CONF_DIR}" "${CONFIG_ZIP}"
-
-#
-# If REALM_FIX is set, we edit the excel files accordingly
-#
-
-if [ -v REALM_FIX ] && [[ "${REALM_FIX}" =~ ^[^=]+=[^=]+$ ]] ; then
-	# REALM_FIX is set as "OLD_VALUE,NEW_VALUE", and three versions are created:
-	# literal (i.e. as-stated), lowercased, and uppercased
-
-	readarray -t -d '=' FIXES < <(echo -n "${REALM_FIX}")
-
-	[ ${#FIXES[@]} -eq 2 ] || fail "The format for REALM_FIX is incorrect - must be 'OLD,NEW': [${REALM_FIX}]"
-
-	OLD="@${FIXES[0]}"
-	NEW="@${FIXES[1]}"
-
-	if [ "${OLD}" != "${NEW}" ] ; then
-		SUBS=("${OLD}" "${NEW}")
-		# If applicable, do the lowercased one
-		[ "${OLD,,}" != "${OLD}" ] && SUBS+=("${OLD,,}" "${NEW,,}")
-		# If applicable, do the uppercased one
-		[ "${OLD^^}" != "${OLD}" ] && SUBS+=("${OLD^^}" "${NEW^^}")
-
-		while read f ; do
-			/fixExcel "${f}" "${SUBS[@]}" || fail "Failed to apply the realm fix for [${f}]"
-		done < <(find "${CONF_DIR}" -type f -name '*.xlsx' | sort)
-	fi
-elif [ -v REALM_FIX ] ; then
-	fail "The format for REALM_FIX is incorrect - must be 'OLD=NEW': [${REALM_FIX}]"
-else
-	say "WARNING: No REALM_FIX found, will not modify the Excel files"
-fi
+realm-fix
 
 #
 # Apply customizations and reconfigurations
 #
 if [ ! -d "${INIT_DIR}" ] ; then
-	COMPLETE="true"
 	say "No initialization to perform, exiting"
 	exit 0
 fi
@@ -152,22 +115,8 @@ while read f ; do
 	[ -x "${f}" ] || continue
 
 	say "Executing initialization script [${f}]..."
-	RC=0
-	OUT="$("${f}")" || RC=${?}
-	[ ${RC} -eq 0 ] || fail "\tInitialization script [${f}] failed (rc=${RC}):\n${OUT}"
+	( "${f}" ) || fail "\tInitialization script [${f}] failed (rc=${?})"
 done < <(list_files)
 
-say "Initialization scripts complete"
-
-say "Deploying the files to their final location"
-cd "${EXTRACT_TARGET}"
-readarray -t FILES < <(list_files)
-# We do it like this so we can run cleanup later if we have to
-for f in "${FILES[@]}" ; do
-	mv -vf "${f}" "${CONF_DIR}"
-done
-
-echo -e "$(date -u -Ins) ${SRC_SUM} ${VER}" &>> "${VERSION_MARKER}"
 say "Configuration Initialization Complete"
-COMPLETE="true"
 exit 0
