Many fixes, added the ability to run initializers

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -1,6 +1,15 @@
 #!/bin/bash
 set -euo pipefail
 
+[ -v BASE_DIR ] || BASE_DIR="/app"
+[ -v CONF_DIR ] || CONF_DIR="${BASE_DIR}/conf"
+[ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"
+CONFIG_ZIP="${BASE_DIR}/.arkcase.zip"
+MARKER="${CONF_DIR}/.arkcase.initialization.complete"
+EXTRACTION="$(mktemp -d -p "${CONF_DIR}")"
+COMPLETE="false"
+FILES=()
+
 say() {
 	echo -e "$(date -u -Isec): ${@}"
 }
@@ -19,24 +28,79 @@ to_boolean() {
 	return 0
 }
 
-[ -v BASE_DIR ] || BASE_DIR="/app"
-[ -v CONF_DIR ] || CONF_DIR="${BASE_DIR}/conf"
+list_files() {
+	local DIR="."
+	[ ${#} -gt 0 ] && DIR="${1}"
+	DIR="$(readlink -f "${DIR}")"
+	if [ -d "${DIR}" ] ; then
+		find "${DIR}" -mindepth 1 -maxdepth 1 | sort | sed -e "s:^${DIR}/::g"
+	else
+		echo "${DIR}"
+	fi
+}
+
+cleanup() {
+	rm -rf "${EXTRACTION}" &>/dev/null
+	if "${COMPLETE}" ; then
+		say "Initialization complete."
+		date -u -Ins &> "${MARKER}"
+	else
+		say "Initialization was not complete. Cleaning out the extracted files"
+		# Just in case ...
+		for f in "${FILES[@]}" ; do
+			f="${CONF_DIR}/${f}"
+			[ -e "${f}" ] || continue
+			rm -rf "${f}"
+		done
+	fi
+}
+
+trap cleanup exit
 
 #
 # Step one: extract the configurations
 #
-CONFIG_ZIP="${BASE_DIR}/.arkcase.zip"
-CONFIG_TGT="${CONF_DIR}/.arkcase"
 
-if [ -d "${CONFIG_TGT}" ] ; then
+if [ -e "${MARKER}" ] ; then
 	say "The configuration appears to already be deployed."
 	exit 0
 fi
 
-mkdir -p "${CONFIG_TGT}"
-cd "${CONFIG_TGT}"
-unzip "${CONFIG_ZIP}"
+[ -d "${CONF_DIR}" ] || fail "Failed to CD into the configuration mount point [${CONF_DIR}]"
+
+# It's OK to do this, as CONF_DIR is meant to be a volume in this container
+unzip -d "${CONF_DIR}" "${CONFIG_ZIP}"
 
 #
-# TODO: Apply customizations and reconfigurations
+# Apply customizations and reconfigurations
 #
+if [ ! -d "${INIT_DIR}" ] ; then
+	say "No initialization to perform, exiting"
+	exit 0
+fi
+
+cd "${INIT_DIR}"
+while read f ; do
+	[ -f "${f}" ] || continue
+	[ -r "${f}" ] || continue
+	[ -x "${f}" ] || continue
+
+	say "Executing initialization script [${f}]..."
+	RC=0
+	OUT="$("${f}")" || RC=${?}
+	[ ${RC} -eq 0 ] || fail "\tInitialization script [${f}] failed (rc=${RC}):\n${OUT}"
+done < <(list_files)
+
+say "Initialization scripts complete"
+
+say "Deploying the files to their final location"
+cd "${EXTRACTION}"
+readarray -t FILES < <(list_files)
+# We do it like this so we can run cleanup later if we have to
+for f in "${FILES[@]}" ; do
+	mv -vf "${f}" "${CONF_DIR}"
+done
+
+say "Configuration Initialization Complete"
+COMPLETE="true"
+exit 0
